try {
    console.log("No Raise);
} catch (exception) {
    console.log("Caught: " + exception);
}